# values for service B

replicaCount: 1

image:
  repository: ealen/echo-server
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: http

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi


probes:
  liveness:
    enabled: true
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    enabled: true
    path: /
    initialDelaySeconds: 3
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  startup:
    enabled: false
    path: /

config:
  data:
    BANNER: "Hello from svc-b (v1)"
    SERVICE_NAME: "svc-b"
secret:
  enabled: true
  stringData:
    SECRET_MESSAGE: "shhh"

serviceAccount:
  create: true

hpa:
  enabled: false
pdb:
  enabled: true
  minAvailable: "50%"

