{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.stringData }}
  {{ $key }}: {{ tpl ($val | toString) $ | quote }}
  {{- end }}
{{- end }}
